'use strict';
/**
 * 厂商预设表。
 *
 * 说明（按 2026-09 各家公开文档核实）：
 *  - DeepSeek / Kimi / OpenRouter 开放了余额接口，填对应 Key 即可查。
 *  - OpenAI 普通 Key 读不到余额，自动降级为「Key 可用性检测」。
 *  - Gemini / Anthropic / 其它 OpenAI 兼容站未开放余额接口，只做 Key 可用性检测。
 * 余额类字段路径均来自官方文档，未验证过的接口一律不写。
 */

const PRESETS = [
  {
    id: 'relay-auto',
    group: '中转站',
    name: '中转站（自动识别）',
    kind: 'relay',
    icon: '🔀',
    baseUrl: '',
    currency: 'USD',
    rawPerUnit: 500000,
    balanceAvailable: true,
    note: 'new-api / one-api 等中转站，自动尝试常见余额接口。部分其他站点需要「系统访问令牌 + 用户 ID」。',
  },
  {
    id: 'deepseek',
    group: '官方厂商',
    name: 'DeepSeek 官方',
    kind: 'balance',
    icon: '🐳',
    baseUrl: 'https://api.deepseek.com',
    path: '/user/balance',
    auth: 'bearer',
    currency: 'CNY',
    rawPerUnit: 1,
    balancePath: 'balance_infos.0.total_balance',
    extraPaths: { 赠送余额: 'balance_infos.0.granted_balance', 充值余额: 'balance_infos.0.topped_up_balance' },
    testPaths: ['/models'],
    balanceAvailable: true,
    note: '官方开放余额接口，只填 Key 即可。',
  },
  {
    id: 'moonshot',
    group: '官方厂商',
    name: 'Kimi / 月之暗面（国内站）',
    kind: 'balance',
    icon: '🌙',
    baseUrl: 'https://api.moonshot.cn',
    path: '/v1/users/me/balance',
    auth: 'bearer',
    currency: 'CNY',
    rawPerUnit: 1,
    balancePath: 'data.available_balance',
    extraPaths: { 代金券余额: 'data.voucher_balance', 现金余额: 'data.cash_balance' },
    testPaths: ['/v1/models'],
    balanceAvailable: true,
    note: '国内站与 platform.kimi.ai 国际站的 Key 不通用。',
  },
  {
    id: 'moonshot-intl',
    group: '官方厂商',
    name: 'Kimi 国际站',
    kind: 'balance',
    icon: '🌙',
    baseUrl: 'https://api.moonshot.ai',
    path: '/v1/users/me/balance',
    auth: 'bearer',
    currency: 'CNY',
    rawPerUnit: 1,
    balancePath: 'data.available_balance',
    extraPaths: { 代金券余额: 'data.voucher_balance', 现金余额: 'data.cash_balance' },
    testPaths: ['/v1/models'],
    balanceAvailable: true,
    note: 'platform.kimi.ai 申请的国际站 Key。',
  },
  {
    id: 'siliconflow',
    group: '官方厂商',
    name: '硅基流动 SiliconFlow',
    kind: 'connectivity',
    icon: '⚡',
    baseUrl: 'https://api.siliconflow.cn',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/v1/models'],
    balanceAvailable: false,
    note: '官方已于 2026-08-14 停用 /v1/user/info，目前只检测 Key；等待官方公布新的余额接口。',
  },
  {
    id: 'zhipu',
    group: '官方厂商',
    name: '智谱 AI / GLM',
    kind: 'connectivity',
    icon: 'Z',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '使用官方 API Key 检测；普通模型 Key 未开放余额接口。',
  },
  {
    id: 'aliyun-bailian',
    group: '官方厂商',
    name: '阿里云百炼 / 通义千问',
    kind: 'connectivity',
    icon: 'Q',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '模型 Key 只做可用性检测；账户余额需使用带签名和 RAM 权限的阿里云 BSS OpenAPI。',
  },
  {
    id: 'volcengine-ark',
    group: '官方厂商',
    name: '火山引擎方舟 / 豆包',
    kind: 'connectivity',
    icon: 'D',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '使用方舟 API Key 检测；普通模型 Key 未开放余额接口。',
  },
  {
    id: 'baidu-qianfan',
    group: '官方厂商',
    name: '百度千帆 / 文心',
    kind: 'connectivity',
    icon: 'B',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '使用千帆 API Key 检测；普通模型 Key 未开放余额接口。',
  },
  {
    id: 'tencent-tokenhub',
    group: '官方厂商',
    name: '腾讯云 TokenHub / 混元',
    kind: 'connectivity',
    icon: 'T',
    baseUrl: 'https://tokenhub.tencentmaas.com/v1',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '使用 TokenHub API Key 检测；旧混元平台计划于 2026-09-30 停服。',
  },
  {
    id: 'minimax-cn',
    group: '官方厂商',
    name: 'MiniMax 国内站',
    kind: 'connectivity',
    icon: 'M',
    baseUrl: 'https://api.minimaxi.com/v1',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '使用国内站 API Key 检测；普通模型 Key 未开放余额接口。',
  },
  {
    id: 'iflytek-spark',
    group: '官方厂商',
    name: '讯飞星火',
    kind: 'connectivity',
    icon: 'X',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    auth: 'bearer',
    currency: 'CNY',
    testPaths: ['/models'],
    balanceAvailable: false,
    note: '密钥填写控制台的 APIPassword；普通模型 Key 未开放余额接口。',
  },
  {
    id: 'openrouter-credits',
    group: '官方厂商',
    name: 'OpenRouter（账户 Credits）',
    kind: 'balance',
    icon: '🔗',
    baseUrl: 'https://openrouter.ai/api',
    path: '/v1/credits',
    auth: 'bearer',
    currency: 'USD',
    rawPerUnit: 1,
    balancePath: 'data.total_credits',
    subtractPath: 'data.total_usage',
    testPaths: ['/v1/key'],
    balanceAvailable: true,
    note: '需要 management key（Provisioning Key），普通 Key 会返回 403。',
  },
  {
    id: 'openrouter-key',
    group: '官方厂商',
    name: 'OpenRouter（单个 Key 剩余额度）',
    kind: 'balance',
    icon: '🔗',
    baseUrl: 'https://openrouter.ai/api',
    path: '/v1/key',
    auth: 'bearer',
    currency: 'USD',
    rawPerUnit: 1,
    balancePath: 'data.limit_remaining',
    testPaths: ['/v1/key'],
    balanceAvailable: true,
    note: '用普通 Key 查。若该 Key 没设额度上限，会取不到值。',
  },
  {
    id: 'openai',
    group: '官方厂商',
    name: 'OpenAI 官方',
    kind: 'billing',
    icon: '🤖',
    baseUrl: 'https://api.openai.com',
    auth: 'bearer',
    currency: 'USD',
    rawPerUnit: 1,
    testPaths: ['/v1/models'],
    balanceAvailable: false,
    note: 'OpenAI 未对普通 API Key 开放余额查询。会先试计费接口，失败则降级为 Key 可用性检测。',
  },
  {
    id: 'anthropic',
    group: '官方厂商',
    name: 'Anthropic Claude 官方',
    kind: 'connectivity',
    icon: '🅰️',
    baseUrl: 'https://api.anthropic.com',
    auth: 'x-api-key',
    extraHeaders: { 'anthropic-version': '2023-06-01' },
    currency: 'USD',
    testPaths: ['/v1/models'],
    balanceAvailable: false,
    note: '官方未开放余额接口，只做 Key 可用性检测。',
  },
  {
    id: 'gemini',
    group: '官方厂商',
    name: 'Google Gemini 官方',
    kind: 'connectivity',
    icon: '✨',
    baseUrl: 'https://generativelanguage.googleapis.com',
    auth: 'query',
    queryParam: 'key',
    currency: 'USD',
    testPaths: ['/v1beta/models'],
    balanceAvailable: false,
    note: '官方未开放余额接口，只做 Key 可用性检测。',
  },
  {
    id: 'compatible',
    group: '官方厂商',
    name: 'OpenAI 兼容站（仅检测 Key）',
    kind: 'connectivity',
    icon: '🧩',
    baseUrl: '',
    auth: 'bearer',
    currency: 'USD',
    testPaths: ['/v1/models', '/models'],
    balanceAvailable: false,
    note: '填自己的地址，只验证 Key 能不能用，查不到余额。',
  },
  {
    id: 'custom',
    group: '自定义',
    name: '自定义余额路径',
    kind: 'custom',
    icon: '🛠',
    baseUrl: '',
    auth: 'bearer',
    currency: 'USD',
    rawPerUnit: 1,
    balanceAvailable: true,
    note: '自己填接口路径和 JSON 取值路径，适配任何非标准站。',
  },
];

const PRESET_MAP = {};
PRESETS.forEach((p) => { PRESET_MAP[p.id] = p; });

function getPreset(id) {
  return PRESET_MAP[id] || PRESET_MAP['relay-auto'];
}

const exported = { PRESETS, getPreset };
if (typeof module !== 'undefined' && module.exports) module.exports = exported;
if (typeof globalThis !== 'undefined') globalThis.APIBalanceProviders = exported;
